### ISSUE TITLE
Duplicate item ingredients are not allowed

### ISSUE THREAD

**Issue by Lgk2** [kingarthur91/PyCoalTBaA#12]
Hey Arthur i'm not sure if this is something i should report to you or to pyanodon or earendel so i'll post it here just in case.
![image](https://user-images.githubusercontent.com/7945495/64927392-b0438b80-d80a-11e9-8316-2ebf892b3222.png)

**Comment by kingarthur91** [comment]
I'll get it taken care of

**Comment by kingarthur91** [comment]
this should be fixed as of 0.9.1
