### ISSUE TITLE
load crash

### ISSUE THREAD

**Issue by Silvernova115** [kingarthur91/PyCoalTBaA#13]
16.122 Error ModManager.cpp:1323: Failed to load mod "PyCoalTBaA": __PyCoalTBaA__/data.lua:10: __PyCoalTBaA__/prototypes/bobs-mods/Data.lua:4: __PyCoalTBaA__/functions/functions.lua:14: bad argument #1 of 3 to 'insert' (table expected, got nil)
stack traceback:
	[C]: in function 'insert'
	__PyCoalTBaA__/functions/functions.lua:14: in function 'add_ingredient'
	__PyCoalTBaA__/prototypes/bobs-mods/overrides/overrides.lua:159: in main chunk
	[C]: in function 'require'
	__PyCoalTBaA__/prototypes/bobs-mods/Data.lua:4: in main chunk
	[C]: in function 'require'
	__PyCoalTBaA__/data.lua:10: in main chunk
stack traceback:
	[C]: in function 'require'
	__PyCoalTBaA__/prototypes/bobs-mods/Data.lua:4: in main chunk
	[C]: in function 'require'
	__PyCoalTBaA__/data.lua:10: in main chunk
stack traceback:
	[C]: in function 'require'
	__PyCoalTBaA__/data.lua:10: in main chun
  16.124 Loading mod core 0.0.0 (data.lua)
  16.288 Checksum for core: 3551490305
  16.338 Error ModManager.cpp:1323: Error in assignID, recipe-category with name 'crafting' does not exist.

Source: default (utility-sprites).
  16.441 Initial atlas bitmap size is 16384
  16.449 Created atlas bitmap 2048x416 [icon, not-compressed, mipmap, linear-minification, linear-magnification, linear-mip-level]
  16.465 Texture processor created (2048). GPU accelerated compression Supported: yes, Enabled: yes/yes. Test passed. YCoCgDXT PSNR: 35.83, BC3 PSNR: 33.82
  16.546 Parallel Sprite Loader initialized (threads: 15)
  16.844 Sprites loaded
  16.866 Generated mipmaps (5) for atlas [0] of size 2048x416   
  16.866 Custom mipmaps uploaded.
  16.869 Factorio initialised
  16.869 Discord overlay detected (DiscordHook64.dll)
  16.873 Mods to disable:Failed to load mods: __PyCoalTBaA__/data.lua:10: __PyCoalTBaA__/prototypes/bobs-mods/Data.lua:4: __PyCoalTBaA__/functions/functions.lua:14: bad argument #1 of 3 to 'insert' (table expected, got nil)
stack traceback:
	[C]: in function 'insert'
	__PyCoalTBaA__/functions/functions.lua:14: in function 'add_ingredient'
	__PyCoalTBaA__/prototypes/bobs-mods/overrides/overrides.lua:159: in main chunk
	[C]: in function 'require'
	__PyCoalTBaA__/prototypes/bobs-mods/Data.lua:4: in main chunk
	[C]: in function 'require'
	__PyCoalTBaA__/data.lua:10: in main chunk
stack traceback:
	[C]: in function 'require'
	__PyCoalTBaA__/prototypes/bobs-mods/Data.lua:4: in main chunk
	[C]: in function 'require'
	__PyCoalTBaA__/data.lua:10: in main chunk
stack traceback:
	[C]: in function 'require'
	__PyCoalTBaA__/data.lua:10: in main chunk

Mods to be disabled:
• PyCoalTBa
  23.806 Quitting: user-quit.
  23.855 Steam API shutdown.
  23.880 Goodbye
 cannot tell what this is

**Comment by kingarthur91** [comment]
im not sure ive got the checks in place so this error should even be possible. can a get a mod list

**Comment by Silvernova115** [comment]
Yea will post one when I get back home

**Comment by Silvernova115** [comment]
[mod list.txt](https://github.com/kingarthur91/PyCoalTBaA/files/3628796/mod.list.txt)
cleaned a few disabled ones up

**Comment by Silvernova115** [comment]
any of bobs mods are causing the crash

**Comment by kingarthur91** [comment]
Doesnt mean much that code is only triggered when Bob's is active so could still be anything that's actually changing the data

**Comment by Silvernova115** [comment]
Yea I know. But I wanted to see what would work. Had just the Bob's library on and and it still crashed. 0.0.53 works though.

**Comment by kingarthur91** [comment]
ok so this issue has been fixed now and will be in the next patch released this sunday. or download the mod from here in the mean time
