### ISSUE TITLE
New crash error 9.1

### ISSUE THREAD

**Issue by Silvernova115** [kingarthur91/PyCoalTBaA#14]
Source: phosphoric-acid-1 (recipe).
 104.594 Initial atlas bitmap size is 16384
 104.594 Created atlas bitmap 2048x512 [icon, not-compressed, mipmap, linear-minification, linear-magnification, linear-mip-level]
 104.623 Texture processor created (2048). GPU accelerated compression Supported: yes, Enabled: yes/yes. Test passed. YCoCgDXT PSNR: 35.83, BC3 PSNR: 33.82
 104.683 Parallel Sprite Loader initialized (threads: 15)
 105.014 Sprites loaded
 105.047 Generated mipmaps (5) for atlas [0] of size 2048x512   
 105.047 Custom mipmaps uploaded.
 105.049 Warning ControlInputValue.cpp:252: Unknown control input string "Control + F"
 105.050 Custom inputs active: 57
 105.053 Factorio initialised
 105.053 Discord overlay detected (DiscordHook64.dll)
 105.059 Mods to disable:Failed to load mods: Error in assignID, fluid with name 'phosphoric-acid' does not exist.

Source: phosphoric-acid-1 (recipe).

Mods to be disabled:
• PyCoalTBaA
 118.697 Quitting: user-quit.
 118.893 Steam API shutdown.
 118.935 Goodbye 

typo maybe?

**Comment by Silvernova115** [comment]
i do not have high tech enabled. and it is trying to pull names of items from pyhightech.

**Comment by kingarthur91** [comment]
ok. thanks ill get it sorted out

**Comment by Silvernova115** [comment]
Do you know when an update to this issue will be out?

**Comment by kingarthur91** [comment]
Sorry been busy. I'll try to get it out friday morning

**Comment by Silvernova115** [comment]
Is the update on github?

**Comment by kingarthur91** [comment]
not yet. it will be soon and ill be pushing out an update at the same time
