### ISSUE TITLE
Wooden Boards Missing

### ISSUE THREAD

**Issue by koriar** [kingarthur91/PyCoalTBaA#15]
Using version 0.9.4 I'm seeing no recipes for Wooden Boards or for Basic Circuit Boards when using Bob's/Angel/Py.

If I enable everything in Bob's/Angel and TBAA, everything seems to work fine.
If I enable everything but Py Ores and TBAA, the game boots and everything seems to work (Except stuff from Py Ores and TBAA obviously)
If I enable everything but Py Ores, Wooden Boards and Basic Circuit Boards are gone.
If I enable absolutely everything, Wooden Boards and Basic Circuit Boards are gone. 

I'm not familiar enough with the mods to say if there's anything else missing.

Let me know if there's any other information I should include.

**Comment by kingarthur91** [comment]
what mods are you actually trying to use. if you can get into the game send a save that i can sync mods/settings with and ill take a look at it

**Comment by koriar** [comment]
[bobangelpy-example-1.zip](https://github.com/kingarthur91/PyCoalTBaA/files/3681325/bobangelpy-example-1.zip)
[2019-1.zip](https://github.com/kingarthur91/PyCoalTBaA/files/3681327/2019-1.zip)

Here's two saves. 2019-1 is what I was actually trying to play, and bobangelpy-example-1 is the trimmed down version that still breaks, to make it easier to isolate the problem.

**Comment by kingarthur91** [comment]
ok i have found the issue. i forgot to check if pyhightech was enabled before disabling the wooden board recipe and basic circuit board. ive fixed it and uploaded the fix to github and you can download it anytime if you like. ill post an update to the mod portal this weekend

**Comment by koriar** [comment]
Thanks!
