### ISSUE TITLE
Tin Smelting in Angels Blastfurnace

### ISSUE THREAD

**Issue by Ldmf** [kingarthur91/PyCoalTBaA#17]
Its imposebel to smelt tin in a angels blastfurnace
We get Bobs Tin but we need Py Tin
change it to bobs tin

same problem with lead

maby its a problem with Angel's Smelting Extended
nop wirh Angel's Smelting Extended so far i can see

<details>
  <summary>Modlist</summary>
  
Additional-Turret-updated
AfraidOfTheDark
air-filtering-patched
alien-biomes
angelsaddons-cab
angelsaddons-insulatedcablecoil
angelsaddons-oresilos
angelsaddons-petrotrain
angelsaddons-pressuretanks
angelsaddons-smeltingtrain
angelsaddons-warehouses
angelsbioprocessing
angelsindustries
angelspetrochem
angelsrefining
angelssmelting
angelssmelting-extended-upgradet
AngelsUsedCoolant
artillery-bombardment-remote
AtomicArtillery
auto-research
AutoDeconstruct
AutoTrash
Barbed-Wire-Light-016
Barrel_Coolant
Better_Angels_Smelting
Better_Strand_Casting
blueprint_flip_and_turn
bobassembly
bobassembly-bigger
bobelectronics
bobenemies
bobequipment
bobinserters
boblibrary
boblogistics
bobmining
bobmodules
bobores
bobplates
bobpower
bobrevamp
bobtech
bobvehicleequipment
bobwarfare
Bob_Power_Fix
bullet-trails
Clowns-AngelBob-Nuclear
Clowns-Extended-Minerals
Clowns-Nuclear
Clowns-Processing
Cold_biters
Command_and_Conquer_Low_Power_Alerts-016
Command_and_Conquer_RedAlert_Sounds
CompressionChests2
crafting_combinator
crazy-cannon
CustomMusicfromMattiasPart1
CustomMusicfromMattiasPart2
deadlock-beltboxes-loaders
deadlock-integrations
deadlock-stacking-crating-bobs
DeadlockCrating
DeadlockLoaders
DeadlocksStacking4Pyanadon
EAB
Enhanced_Map_Colors
ERPTbaAB
even-distribution
EvoGUI
expanded-rocket-payloads
Explosive_biters
extendedangels
factoryplanner
FARL
Fill4Me
floating-damage-text
FNEI
ForceFields2
gas-furnace
Hexy_AngelBob_Tweaks
Hexy_MadClown_Tweaks
IncendiaryMunitions
Infinate_braking_force
invisible-robots
laser_fix
lightArtillery
LogisticTrainNetwork
LSlib
LTN_Combinator
LTN_Content_Reader
LTN_Tracker
m-towerdefense
Manganese_Chrome_Sorting
MilesBobsExpansion
more-petrochem-hell
MushroomCloud
Nanobots
NapalmArtillery
Nuclear_Artillery
OpteraLib
Orbital Ion Cannon
PCPRedux
PickerAtheneum
PickerExtended
PoweredFloor
py-moduless
py-quick-start
PyanodonsFlasks
pycoalprocessing
PyCoalTBaA
pyfunctionnal
pyfusionenergy
pyhightech
pyindustry
pypetroleumhandling
pyrawores
pyscienceorganizer
quickstart-tech
Rampant
Repair_Turret
Rich_Text_Helper
robotworld
robot_attrition
rso-mod
Sandros-fixes
SantasNixieTubeDisplay
ShinyAngelGFX
ShinyBobGFX
SpaceMod
SpaceXGAR
Squeak Through
stdlib
Tiers32
Turret-Shields
VoidFuel
vtk-cannon-turret
YARM
</details>

![20191008232549_1](https://user-images.githubusercontent.com/15316448/66434597-2a8ab880-ea23-11e9-9f5e-e0c69e6fa1d9.jpg)
![20191008232555_1](https://user-images.githubusercontent.com/15316448/66434598-2a8ab880-ea23-11e9-948d-906a38365bc5.jpg)

**Comment by kingarthur91** [comment]
ok can i get a copy of that save file it'll make sync fixing and any migration i need to do much easier

**Comment by Ldmf** [comment]
[WoW.zip](https://github.com/kingarthur91/PyCoalTBaA/files/3705784/WoW.zip)

and thx for you work

igonor py-quick-start it is a fix version from the discort 

[py-quick-start_0.17.4.zip](https://github.com/kingarthur91/PyCoalTBaA/files/3705955/py-quick-start_0.17.4.zip)

if needit

**Comment by kingarthur91** [comment]
ok not sure if it was something about your modpack or if it just broke but the override code for bob ores wasnt working. ive fixed it now for version 0.9.9 which you can download from here other ill release an update to the mod portal in a day or 2

**Comment by Ldmf** [comment]
thx 4 you work hand you help maby somthing went wrong on my end

**Comment by mortess** [comment]
Hi, I have the same issues with the current version of Angels, Bob and Py mods. I've heard that maybe it has some trouble with ores override. Do you know how to fix it please ?

**Comment by Ldmf** [comment]
Try the New Version from her or down grade to the Version bevor 0.9.x

**Comment by Qbotslot** [comment]
Having the same problem still. What files/code were changed so i can add it to my map
