### ISSUE TITLE
Tier 2 science is uncrafrebel if you disable Aluminium Ore and Raw Borax form PyOre

### ISSUE THREAD

**Issue by Ldmf** [kingarthur91/PyCoalTBaA#19]
Save is in my github
https://github.com/Ldmf/Factorio-Saves

You need Duraiumin to craft Tier 2
Duraiumin is craftet from copper and Aluminium Plate

Aluminium Rock is enabeld

![20191027123642_1](https://user-images.githubusercontent.com/15316448/67633935-8aec7780-f8b6-11e9-94cf-30d26817d074.jpg)
![20191027123644_1](https://user-images.githubusercontent.com/15316448/67633936-8aec7780-f8b6-11e9-81d4-18df75ab6cf1.jpg)
![20191027123607_1](https://user-images.githubusercontent.com/15316448/67633937-8b850e00-f8b6-11e9-954d-f625659ed39b.jpg)
![20191027123613_1](https://user-images.githubusercontent.com/15316448/67633938-8b850e00-f8b6-11e9-934f-48a148a32a8c.jpg)
![20191027123617_1](https://user-images.githubusercontent.com/15316448/67633939-8b850e00-f8b6-11e9-8f8b-beb61f372e57.jpg)
![20191027124854_1](https://user-images.githubusercontent.com/15316448/67634100-2d592a80-f8b8-11e9-95dc-bc4b3ce2ed81.jpg)

![20191027133859_1](https://user-images.githubusercontent.com/15316448/67634664-43b6b480-f8bf-11e9-94bb-60a25ff0193f.jpg)

Raw Borax is uncraftebel from synthesis gas

**Only The Aluminium Resavar (Rock or crack in the grund are on) ware you can place the aluminium mine from pymods**

in 0.16 aluminium ore was on Rubyte Ore sorting tier 1

**Comment by Ldmf** [comment]
Titan the same problem ist 4t unlock but it is needit in t3

**Comment by Ldmf** [comment]
Hey king thx 4 the fix

Removed Nicekl ore from sorting
![20191109134453_1](https://user-images.githubusercontent.com/15316448/68528817-fe9b7500-02f7-11ea-9aa9-60e3acdb6123.jpg)

Removed Iron ore from sorting
![20191109134510_1](https://user-images.githubusercontent.com/15316448/68528818-fe9b7500-02f7-11ea-997b-8123856f8e90.jpg)


nothing else fund yet

update github fore save and log and modlist

**Comment by kingarthur91** [comment]
The iron was intended. Use the sapherite?? Ala darker blue ore for iron or there should be like 2 others. 

Do u need the nickel in the early game? At least with pymods you dont and I'm not aware of something that does till after t2

**Comment by Ldmf** [comment]
ok will check with nickel was thinking it is a bug ^^

you can us it for piersing rounds

![20191109142008_1](https://user-images.githubusercontent.com/15316448/68529185-1ecd3300-02fc-11ea-9121-f709b84e773c.jpg)
