### ISSUE TITLE
Little add

### ISSUE THREAD

**Issue by Mutkanum** [kingarthur91/PyCoalTBaA#25]
First of all, I love your great job. But i want to ask for a little more job. I like a mod named "finite wáter" but when used with py, there are two types of saline wáter... If only were posible a better compatibilization….

**Comment by kingarthur91** [comment]
oh. like when using bobs+py? ive never used the mod so ill need to look into it a bit to see whats going on

**Comment by Mutkanum** [comment]
Ok, you are great!
