### ISSUE TITLE
Py-GasVent/Carbon Dioxide - bobs/angels/py

### ISSUE THREAD

**Issue by haineb** [kingarthur91/PyCoalTBaA#26]
I'm running bobs, angels, and pyanodons.

It looks like my Py-GasVent isn't properly disposing of carbon dioxide. The carbon dioxide goes into the stack, but isn't actually disposed of and caps at 1k. It is powered.

Is it possible this is a bug?

**Comment by MECKANIST** [comment]
I also have come across this issue, i find that if its first placed down it works till the game is loaded up again

**Comment by ZXQWAS** [comment]
Use Angel's converter valve, or a sinkhole. Some PY liquids should be gases at their stated temperatures, maybe vice-versa too.

**Comment by caioaletroca** [comment]
Hello, I'm running Py + A + B + Madclowns and another mods, and I can't make Coke because the Tar.  It fits on the Py-GasVent but doesn't get voided.
Since the complexity is too high, I can't produce the Sinkhole (which works well since I tested on a sandbox map).
Do you guys have any ideas? The Py-GasVent was supposed to void the Tar?

**Comment by MECKANIST** [comment]
I was making coke through the pressured furnaces or the angles coal side and no the gas vent is not supposed to void the tar, as the tar is a liquid.

**Comment by ZXQWAS** [comment]
>The Py-GasVent was supposed to void the Tar?

No.


>Do you guys have any ideas?

Use tailings pond. Or convert tar to some gas, but that is probably too farther the line too.

**Comment by caioaletroca** [comment]
Actually, I got it handcrafting a little more science and unlocking the coke process thought burning coal on stone furnaces.

**Comment by haineb** [comment]
Sinkhole works to void the carbon dioxide. Converter valve does not.

I have not experimented with the temperature of the gas impacting ability to void. I haven't gotten my game state to the point where I'm working with temperatures. Is there a test I can do to check if this is working as designed and just a misunderstanding on my part?

**Comment by ZXQWAS** [comment]
This is an old-standing bug, and it is not only CO2 which has it. I don't think there is way for the game to differentiate whether a liquid is a gas or not, as there is no real context for this except the voiders. It is just statically declared somewhere for each substance.
