### ISSUE TITLE
Deadlock's compatibility

### ISSUE THREAD

**Issue by ZXQWAS** [kingarthur91/PyCoalTBaA#3]
At https://forums.factorio.com/viewtopic.php?f=190&t=51967&p=435831#p435831 you didn't mention Deadlock's stacking/crating. Please do. Unless something special was intended for them, like authors of his satellite mods will organize compatibility between themselves using Deadlock's new functions?

**Comment by kingarthur91** [comment]
well before ive never really needed to do anything with them they just kind of worked together as far as i am aware.

its not a high priority but after i get most of the others taken care of i might take some time and add deadlock stacking of stuff directly into the mod so it wont need any extra mods besides deadlocks

**Comment by ZXQWAS** [comment]
@ https://mods.factorio.com/mod/PyCoalTBaA/discussion/5cf3dfbc7bc50c000dbe8d22
It seems that without the current integration, it actually works better. So maybe there's no need to maintain compatibility.

**Comment by ZXQWAS** [comment]
Turned out I can't stack your renamed cm-electronic-circuit, cm-advanced-circuit and cm-processing-unit easily. Would be nice to be able to do that. Maybe there are more items like that.

**Comment by kingarthur91** [comment]
ok. well i havent gotten to that point yet but once i get enough of it done ill be looking into the stacking issues and make sure my stuff is stackable.
