### ISSUE TITLE
issue with Syn Gas and Synthesis Gas

### ISSUE THREAD

**Issue by MECKANIST** [kingarthur91/PyCoalTBaA#31]
[just a note that im using the 9.9 due to the issue with the Py-ores override not working (so that fixes that) but it may be breaking some of the gas.]
     I need chrome for machines and other shit its holding me back form really progressing, however when i go to mine said chromium i require Syn Gas to mine, it [and to be fair iv only really used like one or 2 of the ways to get "Syn Gas" (with the Py Icon) and no mater the way i get Angle's Synthesis gas, leading to the issue of making chromium impossible to get as it will not take Angle's Synthesis gas but requires Py's Syn Gas. 

TLDR: Chrome is impossible to acquire due to a mix up of gases, when attempted to produce Py's Version of Synthesis gas (Syn Gas) one acquires Angle's, which is incompatible with the mine. Similar to the Bob's and Py's Ore mix up and override issue.

[another side note{ this is one hell of a mod pack that iv assembled and i mean like everything, Bob's, Angle's, Py,Space Exploration, AAI shit (not industry because i cant be that fucked) and a fuck ton of QOL mods]
[side note part 2 electric Boogaloo] [I'm no rail way engineer but i can probably tell ya that solder is not used in the construction of rails seems a bit odd for a rail recipe (iron sticks, the treated wood, solder and stone)]
--I can give my save file and other what nots over if you want them.

**Comment by MECKANIST** [comment]
After Looking about, a Decent set of Py Ore patches also seem to have the same issue, somthing wrong with a override somewhere not doing its job, the ones that i explicitly saw was noib and chrom
, i cant remember the rest as its late, if its not a problem i can probably run a fix if I'm told where the files are that need to be modified, I'm also going to slap the save file in this as well for the sake of others if they wish to check this out them selves, but as of now i don't think i can really progress any further with out these more advanced materials 
[Full Bore[MEKIT][Oof[Syn Gas Issue]]v1.2.zip](https://github.com/kingarthur91/PyCoalTBaA/files/3999915/Full.Bore.MEKIT.Oof.Syn.Gas.Issue.v1.2.zip)

**Comment by MECKANIST** [comment]
After doing some digging i have come to a fix for said issue, im posting the file in here, and shall leave open till the devs take and use or fix them selves
this goes in  users/appdata/roaming/factorio/mods/pycoaltbaa/protoypes/angles-mods/overrides
[overrides.zip](https://github.com/kingarthur91/PyCoalTBaA/files/4000610/overrides.zip)

**Comment by ZXQWAS** [comment]
I had this in version 0.0.5x. Using Angel's converter valve fixed it. There was also an unobvious problem with fluid mixing which prevented the flow initially, but I sorted it out somehow.


> im posting the file in here

Perhaps you could do a pull request instead?

**Comment by MECKANIST** [comment]
i had fixed the issue by slapping in the whole if ore-chromium yada yada shit in the overrides but i was unaware of a converter valve, and I'm kinda new to git hub and its projects so im unaware what a pull request does

**Comment by haineb** [comment]
I am running bob/angel/py. I can confirm the bug. The converter valve does not resolve it.

I have applied MECKANIST's fix and can confirm it resolved the issue. I have created PR #32 to integrate it. Thank you.

(There does seem to be some issue with this repository not being up to date with the latest being pushed out to the mod portal.)

**Comment by ProOmicron** [comment]
Add text in file: %AppData%\Roaming\Factorio\mods\PyCoalTBaA_0.9.8\PyCoalTBaA_0.9.8\prototypes\angels-mods\overrides\overrides.lua

if data.raw.resource['ore-chromium'] ~= nil then
if data.raw.fluid['gas-synthesis'] ~= nil then
data.raw.resource['ore-chromium'].minable.required_fluid = 'gas-synthesis'
end
end

if data.raw.resource['ore-zinc'] ~= nil then
if data.raw.fluid['gas-synthesis'] ~= nil then
data.raw.resource['ore-zinc'].minable.required_fluid = 'gas-synthesis'
end
end

if data.raw.resource['ore-nickel'] ~= nil then
if data.raw.fluid['gas-synthesis'] ~= nil then
data.raw.resource['ore-nickel'].minable.required_fluid = 'gas-synthesis'
end
end

This is fixed my problem with Syngas
