### ISSUE TITLE
Failed to load mods

### ISSUE THREAD

**Issue by szentigrad3** [kingarthur91/PyCoalTBaA#37]
246.876 Mods to disable:Failed to load mods: Error while loading recipe prototype "pistol" (recipe): Key "icon" not found in property tree at ROOT.recipe.pistol
Modifications: Base mod › Angel's Refining › Omnimatter › PyCoal Touched By an Angel

Mods to be disabled:
• angelsrefining (0.11.6)
• omnimatter (3.0.8)
• PyCoalTBaA (0.9.10)

**Comment by Whitealbum0** [comment]
I got the same error
sorry Russian
http://prntscr.com/rog5xz

**Comment by Whitealbum0** [comment]
I is deleted this line "heavy-water" and the path to the Data-Final-Fixes.lua file
in fashion angel this function is present "heavy-water"
