### ISSUE TITLE
heavy water bug

### ISSUE THREAD

**Issue by Silvernova115** [kingarthur91/PyCoalTBaA#41]
242.899 Error ModManager.cpp:1469: Error while loading recipe prototype "heavy-water" (recipe): Difficulty normal: Recipe has invalid main product heavy-water. The product does not exist in the recipe product list.
Modifications: Pyanodons Fusion Energy › Angel's Petro Chemical Processing › PyCoal Touched By an Angel
243.819 Crop bitmaps.
243.821 Parallel Sprite Loader initialized (threads: 0)
243.874 Initial atlas bitmap size is 16384
243.875 Created atlas bitmap 2048x816 [icon, not-compressed, mipmap, linear-minification, linear-magnification, linear-mip-level]
243.891 Texture processor created (2048). GPU accelerated compression Supported: yes, Enabled: yes/yes. Test passed. YCoCgDXT PSNR: 35.83, BC3 PSNR: 33.82
243.974 Parallel Sprite Loader initialized (threads: 15)
244.308 Sprites loaded
244.344 Generated mipmaps (5) for atlas [0] of size 2048x816
244.344 Custom mipmaps uploaded.
244.348 Factorio initialised
244.354 Mods to disable:Failed to load mods: Error while loading recipe prototype "heavy-water" (recipe): Difficulty normal: Recipe has invalid main product heavy-water. The product does not exist in the recipe product list.
Modifications: Pyanodons Fusion Energy › Angel's Petro Chemical Processing › PyCoal Touched By an Angel

Halp

**Comment by Samuel-Rider-Leck** [comment]
Yo, I've got a Patch for this!

Open up the zip.
Go to prototypes -> bobs-mods ->Data-Final_Fixes.lua
Change line 7 to `data.raw.recipe["heavy-water"].main_product="liquid-water-heavy"`
rezip everything
Should load afterward

I _haven't testing the recipe with this patch_ but it'll at least let you loaded in.  I /think/ this recipe has been overridden by Angel to have liquid-heavy-water as it's output, see petrochem -> prototypes -> pretrochem-override.lua line 141.
