### ISSUE TITLE
Some weird things

### ISSUE THREAD

**Issue by mecejide** [kingarthur91/PyCoalTBaA#46]
I went hunting for weird things (bugs, oversights, etc.). Here’s the mods I used:
This mod
All of Bob’s mods
Most of Pyanodon’s mods (missing RO and AL)
Helmod
In all cases, I used the newest version of the mod on the portal. Here’s what I found (that hasn’t already been pointed out):
The fluid burning boiler is superior to the oil burner in every way.
There are several electronic components that have multiple recipes, some of which are completely pointless.
All gear wheels besides iron are completely useless.
Sour gas cannot be made.
The oil refineries 2-4 cannot be made.
The tin-rare-earth alloy does not use tin plates, and the cobalt-chromium alloy does not use cobalt plates.

**Comment by kingarthur91** [comment]
Yes its kinda of outdated at the moment. Issues like this are to be expected.

**Comment by mecejide** [comment]
I know it’s outdated. I was just listing them so you knew to fix them.
