### ISSUE TITLE
Heavy-Water + Incentive

### ISSUE THREAD

**Issue by Samwhell** [kingarthur91/PyCoalTBaA#48]
Hello kingarthur91,

I left a more detailed message for you on your mod page:

https://mods.factorio.com/mod/PyCoalTBaA/discussion/5f3814cd45135f5917a8ba5a

But I noticed that its been 5 months since you updated the mod last. I was wondering if there was an incentive I could offer you (I'm talking money here) to get PyCoalTBaA updated and working in Factorio 1.0? I'm not a rich man, but I've put 500 hours into a mod pack and you're the linch pin. If I hear back from you on the mod page message linked above or here we can start hammering out the details as to what would make updating your mod worth your time.

Cheerio,
Samwhell

**Comment by Samwhell** [comment]
Seriously dude. I want to buy your next ten lunches.

**Comment by featherice** [comment]
> Seriously dude. I want to buy your next ten lunches.

Well, looks like currently mod developer works on Pymods as his main project. They are pretty busy. I was hoping to play full abpy modpack too, but it requires a lot of work to update it for new Angel's stuff and just released PyAL. Maybe someone should take over.

**Comment by Samwhell** [comment]
Would if I had the coding fortitude. Maybe I should fix that. I loved that save.

**Comment by kingarthur91** [comment]
ok. sorry github is kind of bad about giving me notifications on things if i miss the emails. ive been working on pycoaltbaa a bit. removed a lot of old trash code. ive currently got it to the point that itll load with angels, bobs, angelbob, omni and currently testing aai industries as i know its one with a few issues. ive got to readd all the item merging code back in so it should be more or less back to functional.

**Comment by Samwhell** [comment]
You're the human, man! Now just find a way to tell me how to tip you and all will be fungshwei with the universe. :-)

**Comment by Samwhell** [comment]
Awww, c'mon bruvnah. let me compensate such a human. Please?

**Comment by Samwhell** [comment]
May a thousand blessings infest your life with the peace of a job well done.
