### ISSUE TITLE
Basic Circuit Board replacement not working correctly.

### ISSUE THREAD

**Issue by Blood-Asp** [kingarthur91/PyCoalTBaA#51]
The circuit board replacement in 
https://github.com/kingarthur91/PyCoalTBaA/blob/master/prototypes/angels-mods/prototypes/overrides/overrides-updates.lua#L4
seems not to work correctly. At last in Foltik's Spaghetti Modpack. The Basic Circuit Boards used in Angels Smelting Machines are not replaced, but the recipe for them is removed, making progession impossible.

**Comment by Blykam** [comment]
I already opened a Bug Report in the Factorio Mod Forum some while ago. He's working on it.

**Comment by kingarthur91** [comment]
ive done some changes and it looks like its working on this end. could i get a save file to check to confirm its working?

**Comment by Blykam** [comment]
[Map Sample.zip](https://github.com/kingarthur91/PyCoalTBaA/files/5700991/Map.Sample.zip)
Here's a sample from me. I updated to TBaA 1.0.1, but it doesn't seem to affect the circuits. Is it life already?

**Comment by Blood-Asp** [comment]
[Map save](https://1drv.ms/u/s!AmaOa6IoyYxHhewMdm1vEio6DnEPAg?e=zYtaam)
[Modpack zip as download ingame does not work correctly in factorio 1.0](https://1drv.ms/u/s!AmaOa6IoyYxHhewNIXD7jQomg4e7gg?e=ua7ME0)

**Comment by Blood-Asp** [comment]
Did check the 1.0.1 version myself too. No fixed circuits. But claybricks are craftable, so better than not updating.

**Comment by kingarthur91** [comment]
ok. found the issue. angels has some code that runs in data-updates that adds basic circuit boards back into some stuff and it was overriding my fixes due to some other mods forcing angels to load after pycoaltbaa was. ive added optional dependencies for all the angels mods to force pycoaltbaa to load after them so it wont break it anymore.

fixed for 1.0.2 release

**Comment by Blykam** [comment]
It works perfectly now. Thank you!

**Comment by Blood-Asp** [comment]
Merry Christmas.

I just noticed that this fix does not work perfectly. The Flotation cell 1 still needs Basic circuit boards. But only this one machine, all others are changed.

**Comment by Blykam** [comment]
> Merry Christmas.
> 
> I just noticed that this fix does not work perfectly. The Flotation cell 1 still needs Basic circuit boards. But only this one machine, all others are changed.

Try using the Py Flotation Cell

**Comment by Blood-Asp** [comment]
There is no Py Flotation Cell. At last not in my modpack

**Comment by Blykam** [comment]
Okay. Now I see what you mean. The flotation cell from Angel's Refining is uncraftable or has no recipe.
I play with Py Raw Ores, which provides also a flotation cell compatible with those recipes.

@kingarthur91 Perhaps a check for installed mods would be better or leaving both recipes in and just changing the pcb recipes.
