### ISSUE TITLE
Crystalmine not buildable

### ISSUE THREAD

**Issue by sebi54668** [kingarthur91/PyCoalTBaA#52]
Started a new game in 1.0,  problem occurs with boblogistics and pycoalprocessing.

Crystalmine Mk 1 (borax-mine in lua) needs:   
ingredients = {
        {"electric-mining-drill", 1},
        {"soil-extractormk01", 1},
        {"electronic-circuit", 20}, --bob basic-electronic-circuit-board
        {"iron-gear-wheel", 15}, --bob steel-bearing
        {"transport-belt", 20}
    },

transport-belt is hidden behind automation science pack, whitch need glas.
For glas you need quartzore and quartzore needs a crystalmine to be mined.

changed it for myself to
 ingredients = {
        {"electric-mining-drill", 1},
        {"soil-extractormk01", 1},
        {"electronic-circuit", 20}, --bob basic-electronic-circuit-board
        {"iron-gear-wheel", 15}, --bob steel-bearing
        {"basic-transport-belt", 20}
    },

**Comment by kingarthur91** [comment]
fixed
