### ISSUE TITLE
petri-dish

### ISSUE THREAD

**Issue by sebi54668** [kingarthur91/PyCoalTBaA#54]
-- fun.global_item_replacer('petri-dish', 'empty-petri-dish')  line 62 in 

https://github.com/kingarthur91/PyCoalTBaA/commit/4b2459d7efc1087634ffe55c27c2e48f944f1e4f?branch=4b2459d7efc1087634ffe55c27c2e48f944f1e4f&diff=unified

 needs to be activated, otherwise Mikroorganism mine won't take them.

**Comment by kingarthur91** [comment]
this is fine on my end. need more details or a save file.

**Comment by sebi54668** [comment]
with the line activated:
![20](https://user-images.githubusercontent.com/75675058/102336211-2fd18480-3f91-11eb-9777-6f8461a82509.png)


without the line:
![21](https://user-images.githubusercontent.com/75675058/102336251-3b24b000-3f91-11eb-8c9b-9328f7ec5538.png)

save:
[2.zip](https://github.com/kingarthur91/PyCoalTBaA/files/5701934/2.zip)
[mod-list.zip](https://github.com/kingarthur91/PyCoalTBaA/files/5701961/mod-list.zip)

**Comment by Erkigmo** [comment]
Should be fixed due to PyAL updates, let me know if this issue persists.
