### ISSUE TITLE
Recipes missing input

### ISSUE THREAD

**Issue by sebi54668** [kingarthur91/PyCoalTBaA#55]
Pictures of them (hopefully most):

![1](https://user-images.githubusercontent.com/75675058/102132038-63a69000-3e53-11eb-8f9a-ae38942213b0.png)
![2](https://user-images.githubusercontent.com/75675058/102132042-64d7bd00-3e53-11eb-9ccb-f25d2dfc818a.png)
![3](https://user-images.githubusercontent.com/75675058/102132045-64d7bd00-3e53-11eb-9918-2564334911e5.png)
![4](https://user-images.githubusercontent.com/75675058/102132047-65705380-3e53-11eb-8dbe-a0729cf6a017.png)
![5](https://user-images.githubusercontent.com/75675058/102132049-65705380-3e53-11eb-8dc8-bfb25d2bd8b4.png)
![6](https://user-images.githubusercontent.com/75675058/102132050-6608ea00-3e53-11eb-899f-b3568d004dc1.png)
![7](https://user-images.githubusercontent.com/75675058/102132053-66a18080-3e53-11eb-9598-b63c516db0f4.png)
![8](https://user-images.githubusercontent.com/75675058/102132056-66a18080-3e53-11eb-9862-8845792f7c08.png)
![9](https://user-images.githubusercontent.com/75675058/102132060-67d2ad80-3e53-11eb-8380-a18d674ef6e6.png)
![10](https://user-images.githubusercontent.com/75675058/102132063-6903da80-3e53-11eb-8969-7a25e051ec40.png)
![11](https://user-images.githubusercontent.com/75675058/102132064-6903da80-3e53-11eb-8059-3af98613268d.png)
![12](https://user-images.githubusercontent.com/75675058/102132065-699c7100-3e53-11eb-80f5-c8a6807f3625.png)
![13](https://user-images.githubusercontent.com/75675058/102132067-699c7100-3e53-11eb-88c7-d9d64077c470.png)
![14](https://user-images.githubusercontent.com/75675058/102132068-6a350780-3e53-11eb-8139-994875beade6.png)
![15](https://user-images.githubusercontent.com/75675058/102132070-6a350780-3e53-11eb-9382-eb10a0d62dac.png)
![16](https://user-images.githubusercontent.com/75675058/102132073-6acd9e00-3e53-11eb-9bd7-4b449e7331fa.png)
![17](https://user-images.githubusercontent.com/75675058/102132074-6acd9e00-3e53-11eb-9e2a-0fb59316c665.png)
![18](https://user-images.githubusercontent.com/75675058/102132078-6b663480-3e53-11eb-8b92-59e2591f1cdf.png)

**Comment by sebi54668** [comment]
found one more
![19](https://user-images.githubusercontent.com/75675058/102202922-3516cc80-3ec8-11eb-8ffa-9b1ab298d01f.png)

**Comment by kingarthur91** [comment]
fixed for next release
