### ISSUE TITLE
sulfur processing 

### ISSUE THREAD

**Issue by infantryman4life** [kingarthur91/PyCoalTBaA#56]
this is the tech that angels over writes and nitrobenzene is not unlocked, so i had to unlock it via console command

![sulfur](https://user-images.githubusercontent.com/60069986/102698772-c651b000-41f4-11eb-9864-452909c49bf7.png)

**Comment by Blood-Asp** [comment]
until there is an official fix, could you tell me the console command? While i know how to enter the commands, i have no idea how to search for internal names of techs, items or other stuff in factorio...

**Comment by Erkigmo** [comment]
Should be fixed due to mod updates
