### ISSUE TITLE
Rare Earth Extractor requires express inserters which require rare earth materials

### ISSUE THREAD

**Issue by KoenHoogendoorn1994** [kingarthur91/PyCoalTBaA#57]
Rare Earth Extractor requires express inserters which require rare earth materials:

Pretty much this.
It's a recipe loop which you cannot start, since you cannot make the complex circuit boards [Bob's electronics] required for the express inserters without having access to the rare earth ore which is mined by the rare earth extractor [Pyanodon's high-tech] which requires express inserters.

Tested with the (mostly) latest versions of all mods involved (no involved recipes changed since those versions according to changelogs):

- Pyanodons Hightech 1.6.9
- Bob's electronics 1.0.1
- PyCoalTBaA 1.0.2

This pretty much blocks progression towards chemical science packs and all further (mostly t3) industrial recipes from angels/bobs/etc, 

If you need any more information on my configuration, please let me know :D 

Kind Regards,

Koen

**Comment by KoenHoogendoorn1994** [comment]
For now I have a workaround with which I can still manage to mine the ore (The mining vehicle from AAI vehicles: Miner), at least until I have enough to make the rare earth extractor.

**Comment by kingarthur91** [comment]
ive found the issue. bob logistics is changing the fast inserter into the express inseter and its making it uncraftable. fixed for 1.0.3.
