### ISSUE TITLE
Printed circuit substrate (tier 1)

### ISSUE THREAD

**Issue by sebi54668** [kingarthur91/PyCoalTBaA#58]
needs Formica <- Melamine resin <- Urea <- Liquid manure <- Manure <- Auog <- cDNA <- Retrovirus <- Vrauk cocoon

for Vrauks you need a Vrauk paddock <- Microorganism mine <- Inserter / Electric mining drill <- Printed circuit substrate (tier 1)

so not doable if 
![22](https://user-images.githubusercontent.com/75675058/103089984-09929100-45f0-11eb-9c8e-8ddc86ace31e.png)
only way to make them.

**Comment by Erkigmo** [comment]
Should be fixed due to Py updates. If this issue persists let me know.
