### ISSUE TITLE
rubber tech being deleted

### ISSUE THREAD

**Issue by kingarthur91** [kingarthur91/PyCoalTBaA#6]
[modlist.txt](https://github.com/kingarthur91/PyCoalTBaA/files/3293026/modlist.txt)

something in that list of mods is deleting the pyph tech for rubber. possibly angels petrochem? or apm

**Comment by ZXQWAS** [comment]
Same as https://mods.factorio.com/mod/PyCoalTBaA/discussion/5ceeb8d57061da000ce30831
There seems to be more stuff affected.

**Comment by Deumiankio** [comment]
> possibly angels petrochem?

You're right, it seems like the pyph tech for rubber is overwritten by the one in angelspetrochem for making rubber from liquid rubber.
This makes it impossible to craft the pyph intermediate item "belt" needed for fast transport belts and other recipes, limiting progression.

**Comment by ZXQWAS** [comment]
I'll duplicate it here, that I accidentally noticed in one of the recent updates a week ago that I'm able to fully use pyPH now for some reason.
