### ISSUE TITLE
Solved: Duralumin Error on Load

### ISSUE THREAD

**Issue by Zostorinqo** [kingarthur91/PyCoalTBaA#60]
Just recently updated to 1.1 and cannot seem to load the game with the sizable amount of mods (from Foltik's Spaghetti Modpack plus additions). I'm not entirely sure which one is specifically causing the error. I'm aware that not everything has updated to 1.1 yet, but these should have been, so there is a strange compatibility error going on here. If it can be determined more accurately what mod is causing it, I'll post on that one specifically.

![FactorioDuraluminError](https://user-images.githubusercontent.com/19249127/103377081-0130cf00-4aa4-11eb-8c16-58dd5b9349b8.png)

Edit: Nevermind, this error has been fixed by using the correct version of PyRO, as the latest release was for 1.0 and not 1.1

**Comment by Blykam** [comment]
You should hit the close button for really closing this issue.
