### ISSUE TITLE
Uncraftable basic circuit boards in Angels's Bio Processing

### ISSUE THREAD

**Issue by cromefire** [kingarthur91/PyCoalTBaA#63]
This seems to be similar to #51 but this time with the `Seed extractor` and `Basic Farm`.

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/26320625/114302414-30a29f00-9ac9-11eb-9575-ce4104280431.png)
![image](https://user-images.githubusercontent.com/26320625/114302430-46b05f80-9ac9-11eb-964d-9fc71a814262.png)

</details>

**Comment by Erkigmo** [comment]
What other mods did you have enabled?

**Comment by Erkigmo** [comment]
Should have been fixed if you used PyHT
