### ISSUE TITLE
Ore merge as of 1.1

### ISSUE THREAD

**Issue by Silvernova115** [kingarthur91/PyCoalTBaA#64]
Bobs and py ores are not merged anymore and it is kind of an issue. I noticed that since 1.0 a lot of stuff was removed I assume is for a fresh restart. are the ores going to be merged at some point? 

also this mod is still being developed?

**Comment by kingarthur91** [comment]
yes it was removed to start over and currently no this isnt really being developed as ive got other things that need worked on and i have lost pretty much all interest in trying to force the major overhauls to work together. its not difficult i just dont have time to look though and check everything. 

when we finish the next pymod im planning to take a look at getting it to work with space exploration and i might revisit this then.

**Comment by Erkigmo** [comment]
I am fixing the ores in dev, an update may come out soon (ish)
