### ISSUE TITLE
Miners that require syngas don't take synthesis gas

### ISSUE THREAD

**Issue by cromefire** [kingarthur91/PyCoalTBaA#65]
Miners that require syngas don't take synthesis gas. Syngas has been replaced by synthesis gas though, so it's impossible to produce.

![image](https://user-images.githubusercontent.com/26320625/119557096-09b1db00-bda0-11eb-8cd8-462527b73dc6.png)

**Comment by Erkigmo** [comment]
Fixed in dev

**Comment by Erkigmo** [comment]
Fixed in dev
