### ISSUE TITLE
[bug] Fluid replacement does not maintain fluidbox indexation, causing start-up crash

### ISSUE THREAD

**Issue by Pezzawinkle** [kingarthur91/PyCoalTBaA#68]
I have recently had a bug come across my desk with relation to the changes to the insulated wire coil casting recipes (from angels extended smelting and compression), due to adding a new fluidbox to the unit I added a fluidbox index to those two recipes...

With those indexes in place (if you have 1 you must have all :( ) the replacement script to use Py's molten metals strips the index's causing the recipe prototype to be invalid.
Not sure if that is a library issue, or an implementation issue on this end.
[Uploading fluidbox_testing.zip…](save file)

![image](https://user-images.githubusercontent.com/54166225/148872046-363b29eb-4b02-4dba-b9d1-ae41a27f7b20.png)

If you need some more details, or the location of the original recipes (to get it to work, I had to remove all indexing to get the map to load), let me know.

**Comment by Erkigmo** [comment]
Fixed
