### ISSUE TITLE
AAI + PyCoal = Bug

### ISSUE THREAD

**Issue by arisu0** [kingarthur91/PyCoalTBaA#7]
Loading just:

Bob mods
AAI industry
PyCoal
PyCoalTBaA

Is as far as I could nail it down.

Error message
Error in assignID, technollogy with name "iron-mk02" does not exist 

Source oil-processing

**Comment by arisu0** [comment]
Does not happen if I load with raw ores instead of  bobs suite

**Comment by Mickleplonk** [comment]
I second this getting the same error.

**Comment by mattregul** [comment]
I only started getting this error once I tried to enabling AAI Industry.

![image](https://user-images.githubusercontent.com/8008527/61086204-3ce35f00-a400-11e9-8d5e-6757e73cd98c.png)

**Comment by Mickleplonk** [comment]
Ok I have added pyanodons raw ores in to the mix and it seems to be working with that.
