### ISSUE TITLE
another loading error

### ISSUE THREAD

**Issue by szentigrad3** [kingarthur91/PyCoalTBaA#75]
https://i.imgur.com/l0WSaHj.png

**Comment by Erkigmo** [comment]
PyCoalTBaA is not yet compatible with omni

**Comment by oorzkws** [comment]
> https://i.imgur.com/l0WSaHj.png

Does this happen without omnimatter present?

**Comment by szentigrad3** [comment]
> > https://i.imgur.com/l0WSaHj.png
> 
> Does this happen without omnimatter present?

it does
https://i.imgur.com/M3NPjVN.png

**Comment by szentigrad3** [comment]
also don't see how you can load angels and py since .. pycoalprocessing is incompat with angelrefining

**Comment by Erkigmo** [comment]
You remove the incompat sign in the info.json

**Comment by notnotmelon** [comment]
https://github.com/pyanodon/pycoalprocessing/commit/57078561a5398c9b613b8280a5f8a2903ad8bf96

**Comment by szentigrad3** [comment]
https://i.imgur.com/EB2DSBL.png

**Comment by Erkigmo** [comment]
Can you post the log?

**Comment by szentigrad3** [comment]
[factorio-current.log](https://github.com/kingarthur91/PyCoalTBaA/files/12597431/factorio-current.log)

**Comment by Erkigmo** [comment]
> https://i.imgur.com/EB2DSBL.png

This should be fixed
