### ISSUE TITLE
crash on load

### ISSUE THREAD

**Issue by mightydanp** [kingarthur91/PyCoalTBaA#82]
![image](https://github.com/kingarthur91/PyCoalTBaA/assets/4637469/61e21a65-6f0d-450e-a300-abac6fe76ed4)
I have bob's Adjustable Inserters, Electronics, functional Library, Logistics, modules 4 PY, Modules, Technology

**Comment by mightydanp** [comment]
Full list

> Bottleneck = "0.11.7",
  CleanedConcreteCompatibility = "1.0.0",
  ["Common-Industries"] = "0.9.3",
  CopyAssemblerPipeDirection = "0.1.4",
  FNEI = "0.4.1",
  LTN_Combinator_Modernized = "2.1.1",
  LTN_Content_Reader = "1.0.3",
  Landfill_plus = "1.0.19",
  LogisticTrainNetwork = "1.18.5",
  LtnManager = "0.4.23",
  PickerAtheneum = "1.2.5",
  PickerBeltTools = "1.2.6",
  PickerBlueprinter = "1.1.6",
  PickerDollies = "1.2.6",
  PickerExtended = "4.1.4",
  PickerFilterFill = "0.0.1",
  PickerInventoryTools = "1.1.15",
  PickerPipeTools = "1.1.4",
  PickerPipeTools_Revisited = "1.1.1",
  PickerTweaks = "2.2.7",
  PickerVehicles = "1.1.3",
  YARM = "0.10.14",
  ["aai-loaders"] = "0.1.4",
  base = "1.1.91",
  beautiful_bridge_railway = "1.1.1",
  bobelectronics = "1.1.6",
  bobinserters = "1.1.7",
  boblibrary = "1.1.6",
  boblogistics = "1.1.6",
  bobmodules = "1.1.6",
  bobsmodules4py = "1.1.8",
  bobtech = "1.1.6",
  ["even-distribution"] = "1.0.10",
  ["extended-descriptions"] = "1.2.1",
  flib = "0.13.0",
  fluidTrains = "1.0.0",
  helmod = "0.12.19",
  ["ltn-cleanup"] = "1.0.17",
  pyalienlife = "2.1.9",
  pyalienlifegraphics = "2.0.5",
  pyalienlifegraphics2 = "2.0.7",
  pyalienlifegraphics3 = "2.0.6",
  pyalternativeenergy = "1.2.6",
  pyalternativeenergygraphics = "1.0.6",
  pycoalprocessing = "2.1.5",
  pycoalprocessinggraphics = "2.0.8",
  pyfusionenergy = "2.0.6",
  pyfusionenergygraphics = "2.0.1",
  pyhardmode = "1.0.7",
  pyhightech = "2.0.10",
  pyhightechgraphics = "2.0.2",
  pyindustry = "2.0.10",
  pypetroleumhandling = "2.1.10",
  pypetroleumhandlinggraphics = "2.0.1",
  pypostprocessing = "0.2.14",
  pyrawores = "2.4.10",
  pyraworesgraphics = "2.0.2",
  ["recipe-tweaker"] = "0.0.7",
  ["rso-mod"] = "6.2.25",
  stdlib = "1.4.8",
  steamTrains = "1.1.0",
  tree_collision = "1.1.0",
  unbarrel = "0.3.0",
  ["undeletable-fluids"] = "1.0.4"

**Comment by mightydanp** [comment]
> 4.613 Error ModManager.cpp:1625: Failed to load mod "PyCoalTBaA": ...pes/bobs-mods/prototypes/overrides/overrides-updates.lua:364: attempt to index field 'alien-science-pack' (a nil value)
stack traceback:
	...pes/bobs-mods/prototypes/overrides/overrides-updates.lua:364: in main chunk
	[C]: in function 'require'
	__PyCoalTBaA__/prototypes/bobs-mods/Data-Updates.lua:2: in main chunk
	[C]: in function 'require'
	__PyCoalTBaA__/data-updates.lua:7: in main chunk
   4.614 Loading mod core 0.0.0 (data.lua)
   4.732 Checksum for core: 466641612
   4.771 Error ModManager.cpp:1625: Error in assignID: recipe-category with name 'crafting' does not exist.

**Comment by Erkigmo** [comment]
You can fix it right now by installing bob's enemies. Will fix it later

**Comment by Erkigmo** [comment]
Fixed
