### ISSUE TITLE
Barreling with barrels doesn't work.

### ISSUE THREAD

**Issue by phooenixdassmatte** [kingarthur91/PyCoalTBaA#94]
![barreling](https://github.com/kingarthur91/PyCoalTBaA/assets/157321203/84eb38b9-85d4-4f34-b670-6832c99167b2)

The barreling machine from angels was previously unlocked when researching fluid barrel processing. But now it is removed and only the barreling machine for pyanodos is craftable, but that can't process regular barrels, only plastic canisters. So regular barrels exists but can't be used.

I still have the angel barreling machines left from before.

![py barreling machine](https://github.com/kingarthur91/PyCoalTBaA/assets/157321203/f93500f4-e636-4a12-b633-1760eb286874)

![2 barreling machines](https://github.com/kingarthur91/PyCoalTBaA/assets/157321203/d3f12a8b-32cf-4822-8409-5cdbab74253f)

Modlist: 
![Modlist](https://github.com/kingarthur91/PyCoalTBaA/assets/157321203/cdd46d19-e519-4399-beab-b07cbc8592bb)

**Comment by Erkigmo** [comment]
Fixed in the latest update

**Comment by phooenixdassmatte** [comment]
Perfect! works now. Only tested with water but i'm sure it works.
