### ISSUE TITLE
Alien artifact research

### ISSUE THREAD

**Issue by phooenixdassmatte** [kingarthur91/PyCoalTBaA#98]
![Alien artifacts](https://github.com/user-attachments/assets/a20c6944-ef30-42b7-ba3e-5555ab1c2cf8)

![Modlist](https://github.com/user-attachments/assets/3ad468f3-40cd-4b24-a7cc-549e55734df2)

**Comment by phooenixdassmatte** [comment]
Note the modlist is the same image as i've used before here, so the mods are exactly the same and updated so the version numbers is different in the picture but everything i have installed is updated.

**Comment by Erkigmo** [comment]
These automatically unlock when you get the small alien artifacts. You can get small alien artifacts from killing biters and, I believe, there's a few recipes for making them.

**Comment by phooenixdassmatte** [comment]
Yes but i have already killed thousands of enemies and researched two of them, but that was a long time ago and alot of stuff have changed since then, could it be that i need to re-trigger that event, picking one up or something?

Or possible revert these two i have researched first and the ones depending on them like the plasma laser and gather turret, then retrigger it by picking up one?

Not really sure how i would write that in the console though.

![artifact researched 2](https://github.com/user-attachments/assets/01062800-6b8f-43a5-a706-02fbb99e8171)

**Comment by Erkigmo** [comment]
Have you gotten any artifacts other then basic and red through killing enemies?

**Comment by phooenixdassmatte** [comment]
Yes i have like 250-350 of each.

![image](https://github.com/user-attachments/assets/cbca31ca-da7f-4b64-b08f-d9f4a506beae)

**Comment by Erkigmo** [comment]
Huh. I'd submit a bug report to angel's, as everything about this should be on their side.

https://github.com/Arch666Angel/mods/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBUG%5D

**Comment by phooenixdassmatte** [comment]
Okey I'll do that, thanks :)
